name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fix:
    if: github.repository == 'fisker/git-hooks-list'
    name: Run automated fix
    uses: fisker/shared-workflows/.github/workflows/automated-fix.yml@main
